### ISSUE TITLE
AndroidX报错

### ISSUE THREAD

**Issue by wangliucheng91** [RookieJay/JWanandroid#1]
ERROR: This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.annotation:annotation:1.0.0
Affected Modules: app

运行的时候报错，
在gradle.properties中添加android.useAndroidX=true 报错更多

**Comment by RookieJay** [comment]
这个项目还没有支持androidX哈 我运行不会出现这个问题呢 gradle版本是3.4.0
