### ISSUE TITLE
通过源码安装得时候 编译成功 手机端未提示 打开权限

### ISSUE THREAD

**Issue by Nwooooo** [RookieJay/JWanandroid#3]
通过源码安装得时候编译成功，安装成功
 手机端未提示 打开权限 但是在 AndroidManifest中 有   
 <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
请问在哪设置安装提示权限
ps：测试手机 红米8p 华为p20 均无权限提示

**Comment by RookieJay** [comment]
动态申请的权限只有相机和储存权限，没提示就说明授权了吧。你看看应用设置里面有没有呢

**Comment by Nwooooo** [comment]
经过确认 没有。。。。

**Comment by RookieJay** [comment]
我想起来了 要登录以后点击头像才会申请 一开始使用是没有的 现在你能正常使用app吗

**Comment by Nwooooo** [comment]
不登录wanandroid 的账号光浏览文章和查询 完全没问题

**Comment by RookieJay** [comment]
那还有啥问题吗？
