### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by s3abiscuit** [RookieJay/JWanandroid#6]
Could not get unknown property 'buglyAppId' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

**Comment by RookieJay** [comment]
> Could not get unknown property 'buglyAppId' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

有几个办法：
1.自己去bugly申请一个id,然后在gradle.properties下面添加buglyAppId=【你申请到的id】
2.注释掉JApplication的onCreate方法下的，Bugly.init调用，以及注释掉build.gradle(app)下的两行buildConfigField("string", "BUGLY_APP_ID", "${buglyAppId}")
