### ISSUE TITLE
Could not get unknown property 'buglyAppId' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

### ISSUE THREAD

**Issue by BatesLi** [RookieJay/JWanandroid#7]
Could not get unknown property 'buglyAppId' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

下载之后，用AS4.0版本运行，老是出现这个错误。

**Comment by RookieJay** [comment]
[尝试这个](https://github.com/RookieJay/JWanandroid/issues/6#issuecomment-753766452)

**Comment by RookieJay** [comment]
更新下代码吧，应该可以了。
